name: Test
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  test:
    name: Unit test for latest dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Remove package-lock.json
        run: rm -f package-lock.json
      - name: Install NPM dependencies
        run: npm i
      - name: Check dependencies size
        run: du -sh node_modules
      - name: Unit test using Jest
        run: npm run test
